AWSTemplateFormatVersion: 2010-09-09
Transform: "AWS::Serverless-2016-10-31"
Description: Unionize app

Parameters:
  LogLevel:
    Type: String
    Default: info
  ApplicationName:
    Type: String
    Default: unionize

Resources:
  UnionizeApi:
    Type: AWS::Serverless::Application
    Properties:
      Location: api.yml
      Parameters:
        ApplicationName: !Ref ApplicationName

  UnionStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: union.yml
      Parameters:
        ApplicationName: !Ref ApplicationName
        LogLevel: !Ref LogLevel
        RestApiId: !GetAtt UnionizeApi.Outputs.RestApiId
        RestApiRootId: !GetAtt UnionizeApi.Outputs.RestApiRootId

  UnionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: unionize-unions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "unionName"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "unionName"
          KeyType: HASH
