AWSTemplateFormatVersion: 2010-09-09
Transform: "AWS::Serverless-2016-10-31"
Description: Unionize app

Parameters:
  LogLevel:
    Type: String
    Default: info

Resources:
  UnionStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: union.yml
      Parameters:
        LogLevel: !Ref LogLevel

  UnionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: unionize-unions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "unionName"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "unionName"
          KeyType: HASH
