AWSTemplateFormatVersion: 2010-09-09
Transform: "AWS::Serverless-2016-10-31"
Description: Unionize app

Parameters:
  LogLevel:
    Type: String
    Default: info
  ApplicationName:
    Type: String
    Default: unionize

Resources:
  UnionizeApi:
    Type: AWS::Serverless::Application
    Properties:
      Location: api.yml
      Parameters:
        ApplicationName: !Ref ApplicationName

  UnionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${ApplicationName}-unions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "unionName"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "unionName"
          KeyType: HASH

  WorkerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${ApplicationName}-workers
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "unionName"
          AttributeType: "S"
        - AttributeName: "encodedContactHash"
          AttributeType: "S"
        - AttributeName: "encodedPhone"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "unionName"
          KeyType: HASH
        - AttributeName: "encodedContactHash"
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: encodedPhone
          KeySchema:
            - AttributeName: "encodedPhone"
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  UnionStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: union.yml
      Parameters:
        ApplicationName: !Ref ApplicationName
        LogLevel: !Ref LogLevel
        RestApiId: !GetAtt UnionizeApi.Outputs.RestApiId
        RestApiRootId: !GetAtt UnionizeApi.Outputs.RestApiRootId
        UnionTableName: !Ref UnionTable
        WorkerTableName: !Ref WorkerTable

  WorkerStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: worker.yml
      Parameters:
        ApplicationName: !Ref ApplicationName
        LogLevel: !Ref LogLevel
        RestApiId: !GetAtt UnionizeApi.Outputs.RestApiId
        RestApiRootId: !GetAtt UnionizeApi.Outputs.RestApiRootId
        UnionCreatedTopicArn: !GetAtt UnionStack.Outputs.UnionCreatedTopicArn
        WorkerTableName: !Ref WorkerTable

  SMSStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: sms.yml
      Parameters:
        ApplicationName: !Ref ApplicationName
        LogLevel: !Ref LogLevel
        WorkerTableName: !Ref WorkerTable
        WorkerAcceptedSMSInviteTopicArn: !GetAtt WorkerStack.Outputs.WorkerAcceptedSMSInviteTopicArn
        UnionMessageReceivedTopicArn: !GetAtt UnionStack.Outputs.UnionMessageReceivedTopicArn
