AWSTemplateFormatVersion: 2010-09-09
Transform: "AWS::Serverless-2016-10-31"
Description: Unionize app

Parameters:
  LogLevel:
    Type: String
    Default: info

Resources:
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      ApiKeySourceType: HEADER
      Name: !Sub unionize-api

  UnionStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: union.yml
      Parameters:
        LogLevel: !Ref LogLevel
        RestApiId: !Ref RestApi
        RestApiRootId: !GetAtt RestApi.RootResourceId

  UnionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: unionize-unions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "unionName"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "unionName"
          KeyType: HASH
