AWSTemplateFormatVersion: 2010-09-09
Transform: "AWS::Serverless-2016-10-31"
Description: Worker specific Resources

Parameters:
  ApplicationName:
    Type: String
  LogLevel:
    Type: String
  RestApiId:
    Type: String
  RestApiRootId:
    Type: String
  UnionCreatedTopicArn:
    Type: String

Resources:
  WorkerGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApiId
      PathPart: worker
      ParentId: !Ref RestApiRootId

  WorkerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${ApplicationName}-workers
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "unionName"
          AttributeType: "S"
        - AttributeName: "encodedContactHash"
          AttributeType: "S"
        - AttributeName: "encodedPhone"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "unionName"
          KeyType: HASH
        - AttributeName: "encodedContactHash"
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: encodedPhone
          KeySchema:
            - AttributeName: "encodedPhone"
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  # Invite Resources
  InviteWorkerHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ApplicationName}-invite-worker
      Runtime: python3.10
      Handler: handlers/worker/invite.handler
      Policies:
        - AmazonSNSFullAccess
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref WorkerTable
      Environment:
        Variables:
          LogLevel: !Ref LogLevel

  InviteWorkerPermission:
    DependsOn: InviteWorkerHandler
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Sub ${ApplicationName}-invite-worker
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com

  InviteWorkerPathResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApiId
      PathPart: invite
      ParentId: !Ref WorkerGatewayResource

  InviteWorkerMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref InviteWorkerPathResource
      HttpMethod: POST
      ApiKeyRequired: true
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${InviteWorkerHandler.Arn}/invocations

  # SignUp Resources
  SignUpWorkerHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ApplicationName}-sign-up-worker
      Runtime: python3.10
      Handler: handlers/worker/sign_up.handler
      Policies:
        - AmazonSNSFullAccess
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref WorkerTable
      Environment:
        Variables:
          LogLevel: !Ref LogLevel

  SignUpWorkerPermission:
    DependsOn: SignUpWorkerHandler
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Sub ${ApplicationName}-sign-up-worker
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com

  SignUpWorkerPathResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApiId
      PathPart: signup
      ParentId: !Ref WorkerGatewayResource

  SignUpWorkerMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref SignUpWorkerPathResource
      HttpMethod: POST
      ApiKeyRequired: true
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${SignUpWorkerHandler.Arn}/invocations

  # Add Worker To Union Resources
  AddWorkerToUnionQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${ApplicationName}-add-worker-to-union-q
      VisibilityTimeout: 10
      ReceiveMessageWaitTimeSeconds: 2
      RedrivePolicy:
        maxReceiveCount: 3
        deadLetterTargetArn: arn:aws:sqs:us-east-1:487170294390:test-queue

  AddWorkerToUnionHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ApplicationName}-add-worker-to-union
      Runtime: python3.10
      Handler: handlers/worker/add_to_union.handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonSNSFullAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref WorkerTable
      Events:
        AddWorkerToUnionQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt AddWorkerToUnionQueue.Arn
            BatchSize: 1
      Environment:
        Variables:
          LogLevel: !Ref LogLevel

  UnionCreatedSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref UnionCreatedTopicArn
      Endpoint: !GetAtt AddWorkerToUnionQueue.Arn
      RawMessageDelivery: True
      Protocol: sqs

  WorkerAcceptedSMSInviteTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${ApplicationName}-worker-accepted-sms-invite

  WorkerAcceptedSMSInviteSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref WorkerAcceptedSMSInviteTopic
      Endpoint: !GetAtt AddWorkerToUnionQueue.Arn
      RawMessageDelivery: True
      Protocol: sqs

  # We have to add this otherwise the SNS topics cannot send to SQS
  UnionCreatedSubscriptionPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref AddWorkerToUnionQueue
      PolicyDocument:
        Version: "2012-10-17"
        Id: SNSUnionCreatedQueuePolicy
        Statement:
          - Effect: Allow
            Sid: Allow-SNS-SendMessage
            Principal:
              Service: sns.amazonaws.com
            Action:
              - sqs:SendMessage
              - sqs:SendMessageBatch
            Resource: !GetAtt AddWorkerToUnionQueue.Arn

Outputs:
  WorkerTableName:
    Description: "The specific name of the table storing worker data, for use in access policies in other stacks"
    Value: !Ref WorkerTable
  WorkerAcceptedSMSInviteTopic:
    Value: !Ref WorkerAcceptedSMSInviteTopic
